#!/usr/bin/env bash
# setup-wsl-libs.sh — copy WSL2 NVIDIA driver libraries to ~/wsl-libs so the
# confined snap-docker can bind-mount them into the thermocline GPU container.
#
# Why: snap docker runs in its own mount namespace and cannot see /usr/lib/wsl/
# (read-only 9p from Windows). But it CAN see $HOME. So we copy the loader
# stubs + the real driver-store libs there, then docker-compose bind-mounts
# ~/wsl-libs into the container at the exact paths the WSL CUDA loader expects.
#
# The loader (libcuda.so.1, 183KB) queries /dev/dxg to discover the driver
# store path /usr/lib/wsl/drivers/nv_dispsi.inf_amd64_<HASH>/, then dlopen's
# the real libcuda.so.1.1 (26MB) from that dir. The <HASH> is Windows-driver-
# specific; this script detects it and writes .env for docker-compose.
#
# Run once after a Windows NVIDIA driver update:
#   bash docker/setup-wsl-libs.sh

set -euo pipefail

WSL_LIB=/usr/lib/wsl/lib
WSL_DRIVERS=/usr/lib/wsl/drivers
DEST="${HOME}/wsl-libs"

# Find the NVIDIA driver store dir (nv_dispsi.inf_amd64_<hash>).
DRV_DIR=$(ls -d "${WSL_DRIVERS}"/nv_dispsi.inf_amd64_* 2>/dev/null | head -1 || true)
if [[ -z "${DRV_DIR}" ]]; then
  echo "ERROR: no NVIDIA driver store found under ${WSL_DRIVERS}/nv_dispsi.inf_amd64_*" >&2
  echo "       Is this WSL2 with NVIDIA drivers installed on Windows?" >&2
  exit 1
fi
DRV_NAME=$(basename "${DRV_DIR}")

echo ">> NVIDIA driver store: ${DRV_NAME}"

rm -rf "${DEST}"
mkdir -p "${DEST}/lib" "${DEST}/drivers"

# Loader stubs from /usr/lib/wsl/lib (libcuda.so.1, libdxcore.so, libnvidia-ml.so.1).
echo ">> copying loader stubs from ${WSL_LIB}"
cp "${WSL_LIB}"/libcuda.so.1 "${WSL_LIB}"/libdxcore.so "${WSL_LIB}"/libnvidia-ml.so.1 "${DEST}/lib/"

# Real driver libs from the driver store (protected → sudo).
echo ">> copying real driver libs from ${DRV_DIR} (sudo needed)"
sudo cp \
  "${DRV_DIR}"/libcuda.so.1.1 \
  "${DRV_DIR}"/libcuda_loader.so \
  "${DRV_DIR}"/libnvidia-ptxjitcompiler.so.1 \
  "${DRV_DIR}"/libnvidia-ml.so.1 \
  "${DRV_DIR}"/libnvidia-ml_loader.so \
  "${DRV_DIR}"/libnvdxgdmal.so.1 \
  "${DRV_DIR}"/nvcubins.bin \
  "${DEST}/drivers/" 2>/dev/null || true
sudo chown -R "$(id -u):$(id -g)" "${DEST}/drivers/"

# Write .env so docker-compose knows the driver-store dir name + libs path.
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup-wsl-libs.sh — do not edit.
# The NVIDIA driver store dir name (Windows-driver-specific hash).
WSL_DRIVER_DIR=${DRV_NAME}
# Absolute path to the copied libs (snap docker CLI has a snapped HOME, so
# ~/wsl-libs would resolve to /home/<user>/snap/docker/... — use absolute).
WSL_LIBS_DIR=${DEST}
EOF

echo ""
echo ">> Done. WSL libs at ${DEST}"
echo ">> Wrote ${ENV_FILE} with WSL_DRIVER_DIR=${DRV_NAME}"
echo ""
echo "Now build + run GPU variant:"
echo "  docker compose -f docker/docker-compose.yml --profile gpu up -d --build"
